package com.nhatvm.core.designsystem.theme

import androidx.compose.ui.graphics.Color

val light_primary = Color(0xFFA93800)
val light_onPrimary = Color(0xFFFFFFFF)
val light_primaryContainer = Color(0xFFFFDBCF)
val light_onPrimaryContainer = Color(0xFF380D00)
val light_secondary = Color(0xFF00658B)
val light_onSecondary = Color(0xFFFFFFFF)
val light_secondaryContainer = Color(0xFFC4E7FF)
val light_onSecondaryContainer = Color(0xFF001E2C)
val light_tertiary = Color(0xFF006973)
val light_onTertiary = Color(0xFFFFFFFF)
val light_tertiaryContainer = Color(0xFF90F1FF)
val light_onTertiaryContainer = Color(0xFF001F23)
val light_error = Color(0xFFBA1A1A)
val light_errorContainer = Color(0xFFFFDAD6)
val light_onError = Color(0xFFFFFFFF)
val light_onErrorContainer = Color(0xFF410002)
val light_background = Color(0xFFFFFBFF)
val light_onBackground = Color(0xFF201A18)
val light_surface = Color(0xFFFFFBFF)
val light_onSurface = Color(0xFF201A18)
val light_surfaceVariant = Color(0xFFF5DED6)
val light_onSurfaceVariant = Color(0xFF53433E)
val light_outline = Color(0xFF85736D)
val light_inverseOnSurface = Color(0xFFFBEEEA)
val light_inverseSurface = Color(0xFF362F2C)
val light_inversePrimary = Color(0xFFFFB59B)
val light_shadow = Color(0xFF000000)
val light_surfaceTint = Color(0xFFA93800)
val light_outlineVariant = Color(0xFFD8C2BB)
val light_scrim = Color(0xFF000000)

val dark_primary = Color(0xFFFFB59B)
val dark_onPrimary = Color(0xFF5B1B00)
val dark_primaryContainer = Color(0xFF812900)
val dark_onPrimaryContainer = Color(0xFFFFDBCF)
val dark_secondary = Color(0xFF7DD0FF)
val dark_onSecondary = Color(0xFF00344A)
val dark_secondaryContainer = Color(0xFF004C69)
val dark_onSecondaryContainer = Color(0xFFC4E7FF)
val dark_tertiary = Color(0xFF4ED8E9)
val dark_onTertiary = Color(0xFF00363C)
val dark_tertiaryContainer = Color(0xFF004F57)
val dark_onTertiaryContainer = Color(0xFF90F1FF)
val dark_error = Color(0xFFFFB4AB)
val dark_errorContainer = Color(0xFF93000A)
val dark_onError = Color(0xFF690005)
val dark_onErrorContainer = Color(0xFFFFDAD6)
val dark_background = Color(0xFF201A18)
val dark_onBackground = Color(0xFFEDE0DC)
val dark_surface = Color(0xFF201A18)
val dark_onSurface = Color(0xFFEDE0DC)
val dark_surfaceVariant = Color(0xFF53433E)
val dark_onSurfaceVariant = Color(0xFFD8C2BB)
val dark_outline = Color(0xFFA08D86)
val dark_inverseOnSurface = Color(0xFF201A18)
val dark_inverseSurface = Color(0xFFEDE0DC)
val dark_inversePrimary = Color(0xFFA93800)
val dark_shadow = Color(0xFF000000)
val dark_surfaceTint = Color(0xFFFFB59B)
val dark_outlineVariant = Color(0xFF53433E)
val dark_scrim = Color(0xFF000000)


val seed = Color(0xFFFF6C2F)